version: '2'
services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=austria_rulers
    ports:
    - '127.0.0.1:5432:5432'
  redis:
    image: redis
    ports:
    - '127.0.0.1:6379:6379'
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py full_ruler_update && python manage.py runserver 0.0.0.0:8000"
    env_file: common.env
    depends_on:
    - db
    - redis
    links:
    - db:db
    - redis:redis
    ports:
    - '8000:8000'
    volumes:
    - .:/app:Z
