# Generated by Django 2.0.1 on 2018-02-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('ruler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruler_requests', to='rulers.Ruler', verbose_name='Правитель')),
                ('ruler_successors', models.ManyToManyField(related_name='ruler_requests_as_successor', to='rulers.Ruler', verbose_name='Вычисленные наследники (на момент запроса)')),
            ],
        ),
    ]
